name: my_project_name

services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "33067:3306"
    networks:
      app-network:

  web:
    build: ./django_app
    depends_on:
      - db
    volumes:
      - ./django_app:/django_app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}  # 使用root密码
    networks:
      app-network:

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

#    name: my_project_name

#    services:
#      db:
#        image: "mysql:8.0.36"
#        container_name: "mysql-server"
#        restart: unless-stopped
#        command:
#          # 使用 mysql_native_password 插件（8 版本中已过时）
#          # - --default-authentication-plugin=mysql_native_password
#          - --default-authentication-plugin=caching_sha2_password
#          - --character-set-server=utf8
#          - --collation-server=utf8_general_ci
#          # 启用显式默认值
#          - --explicit_defaults_for_timestamp=true
#        volumes:
#          - 'db_data:/var/lib/mysql'
#          # 用于初始化数据库
#          # 需要修改
#          - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
#          # MySQL 配置文件
#        environment:
#          # 时区
#          - TZ=Asia/Shanghai
#          # 数据库密码
#          - MYSQL_ROOT_PASSWORD=123456
#          # 数据库名称
#          - MYSQL_DATABASE=glass_analysis
#          # 数据库用户名
#          - MYSQL_USER=django_user
#          # 数据库密码
#          - MYSQL_PASSWORD=django_password
#        ports:
#          - "33067:3306"
#        tty: true
#        stdin_open: true
#        logging:
#          driver: "json-file"
#          options:
#            # 最大日志文件大小
#            max-size: "1G"
#            # 最大日志文件数量
#            max-file: "5"
#        healthcheck:
#          test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
#          interval: 30s
#          timeout: 10s
#          retries: 5
#          start_period: 10s
#        networks:
#          # from __base-net.yml
#          app-network:
#
#      web:
#        build: ./django_app
#        depends_on:
#          - db
#        volumes:
#          - ./django_app:/django_app
#        ports:
#          - "8000:8000"
#        environment:
#          - DB_HOST=db
#          - DB_NAME=${DB_NAME}
#          - DB_USER=root
#          - DB_PASSWORD=${DB_ROOT_PASSWORD}  # 使用root密码
#        networks:
#          app-network:
#
#    networks:
#      app-network:
#        driver: bridge
#
#    volumes:
#      db_data:


