# Generated by Django 5.1.7 on 2025-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, verbose_name='月份')),
                ('product', models.CharField(max_length=50, verbose_name='产品')),
                ('sales_volume', models.FloatField(blank=True, null=True, verbose_name='销售量')),
                ('sales_amount', models.FloatField(verbose_name='销售额')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='成本')),
                ('gross_margin', models.FloatField(verbose_name='毛利率')),
                ('unit_price', models.FloatField(verbose_name='单价')),
                ('material_ratio', models.FloatField(verbose_name='材料比例')),
                ('major_client', models.CharField(max_length=100, verbose_name='主要客户')),
            ],
            options={
                'verbose_name': '销售数据',
                'verbose_name_plural': '销售数据',
            },
        ),
    ]
